### ISSUE TITLE
Fix reloading of survey/preview

### ISSUE THREAD

**Issue by soumyaray** [SurveyMoonBear/SurveyMoonbear_APP#34]
Right now, when someone on survey or preview reloads the page or enters the page through URL, the platform disregards any page specified in the url, e.g., `#page_2`.

Make sure when someone on survey or preview reloads the page or enters the page through URL, we direct them to the right page in the url.

**Comment by soumyaray** [comment]
Check if survey data lost on reload (it should be). If so, for launch survey, just take them back to first page, and remove URL's page value attribute

Keep reload on page feature for preview!!!

**Comment by soumyaray** [comment]
@ShellyHsueh what conclusions from fixing this?

**Comment by soumyaray** [comment]
@NicholasDanks might want to hear what is happening here as well.

**Comment by ShellyHsueh** [comment]
@soumyaray @NicholasDanks Now, reloading in survey preview page should keep in the same location of the same page. Survey creators can simply refresh the preview page to check the changes after making ones in spreadsheets. 
However, in the started-survey page, respondents' refreshing page should still lead them to the first page because it resets their responses.

**Comment by soumyaray** [comment]
Thanks @ShellyHsueh !
